In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv('datasets/data_center_hybrid.csv')
data.head()

,Year,Facility_ID,Facility_Name,Owner_Company,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low

In [3]:
data.describe()

,Year,Estimated_Capacity_MW,PUE,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons
count,126770.000000,126770.000000,126770.000000,126770.000000,126770.000000,1.267700e+05
mean,2022.000000,23.075117,1.637746,0.820596,605.222368,1.312182e+05
std,2.000008,45.847195,0.190833,0.925481,1040.061940,3.979629e+05
min,2019.000000,1.000000,1.057000,0.001000,22.190000,2.240100e+02
25%,2020.000000,5.450000,1.518000,0.139000,167.432500,4.840538e+03
50%,2022.000000,9.870000,1.643000,0.232000,302.750000,1.218130e+04
75%,2024.000000,14.180000,1.787000,1.654000,451.370000,7.573068e+04
max,2025.000000,562.890000,2.000000,3.000000,14812.660000,7.585092e+06

In [4]:
data.isnull().sum()

Year                             0
Facility_ID                      0
Facility_Name                    0
Owner_Company                    0
City                             0
Country                          0
Facility_Type                    0
Estimated_Capacity_MW            0
PUE                              0
Cooling_System_Type              0
WUE_L_per_kWh                    0
Daily_Electricity_Usage_MWh      0
Daily_Water_Usage_Gallons        0
Surrounding_Water_Stress_Tier    0
dtype: int64

In [5]:
data.isnull().any(axis=1)

0         False
1         False
2         False
3         False
4         False
          ...
126765    False
126766    False
126767    False
126768    False
126769    False
Length: 126770, dtype: bool

In [6]:
data.rename(columns={'Owner_Company':'Owner'},inplace=True)
data.head()

,Year,Facility_ID,Facility_Name,Owner,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low

In [15]:
# change datatypes 
data['Rounded_Estimated_Capacity_MW']=data['Estimated_Capacity_MW'].astype(int)
data.head()

,Year,Facility_ID,Facility_Name,Owner,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier,Rounded_Estimated_Capacity_MW
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low,6
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low,6
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low,6
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low,6
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low,6

In [16]:
data['Surrounding_Water_Stress_Tier'].unique()

<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

In [17]:
def change_root(type):
    if type=='Low':
        return -1 
    if type=='Medium':
        return 1 
    if type=='High':
        return 1
    
data['Req']=data['Surrounding_Water_Stress_Tier'].apply(change_root)
data

,Year,Facility_ID,Facility_Name,Owner,City,Country,Facility_Type,Estimated_Capacity_MW,PUE,Cooling_System_Type,WUE_L_per_kWh,Daily_Electricity_Usage_MWh,Daily_Water_Usage_Gallons,Surrounding_Water_Stress_Tier,Rounded_Estimated_Capacity_MW,Req
0,2019,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.24,1.975,Evaporative,1.481,183.62,36362.94,Low,6,-1
1,2020,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.36,1.967,Evaporative,1.459,254.34,49833.60,Low,6,-1
2,2021,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.47,1.928,Evaporative,1.450,266.85,53026.35,Low,6,-1
3,2022,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.59,1.897,Evaporative,1.413,199.14,39198.30,Low,6,-1
4,2023,DC-D2763E00,NAP de las Americas Madrid,Terremark,Madrid,Spain,Enterprise/Standard,6.70,1.869,Evaporative,1.389,225.94,44366.48,Low,6,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126765,2021,DC-31D8B15E,ICS_DataCenter_216,ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLE...,Unknown,Türkiye,Enterprise/Standard,14.51,1.495,Evaporative,2.305,381.65,155454.82,High,14,1
126766,2022,DC-31D8B15E,ICS_DataCenter_216,ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLE...,Unknown,Türkiye,Enterprise/Standard,14.77,1.485,Evaporative,2.281,378.59,153627.09,High,14,1
126767,2023,DC-31D8B15E,ICS_DataCenter_216,ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLE...,Unknown,Türkiye,Enterprise/Standard,15.04,1.473,Evaporative,2.245,319.36,128626.89,High,15,1
126768,2024,DC-31D8B15E,ICS_DataCenter_216,ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLE...,Unknown,Türkiye,Enterprise/Standard,15.31,1.450,Evaporative,2.231,394.69,160407.53,High,15,1
126769,2025,DC-31D8B15E,ICS_DataCenter_216,ICS BİLİŞİM TEKNOLOJİLERİ DANIŞMANLIK HİZMETLE...,Unknown,Türkiye,Enterprise/Standard,15.58,1.431,Evaporative,2.217,463.45,189650.23,High,15,1

# aggregation

In [21]:
grouped_data=data.groupby(['Cooling_System_Type'])['Daily_Water_Usage_Gallons'].mean()
grouped_data

Cooling_System_Type
Air Cooled        11665.694138
Evaporative      342348.459332
Liquid Cooled     56541.645937
Name: Daily_Water_Usage_Gallons, dtype: float64

In [23]:
grouped_data=data.groupby(['Cooling_System_Type'])['Daily_Water_Usage_Gallons'].agg(['min','mean','max'])
grouped_data

                         min           mean         max
Cooling_System_Type
Air Cooled            224.01   11665.694138   690806.40
Evaporative          5153.30  342348.459332  7585092.35
Liquid Cooled         781.12   56541.645937   497485.71

In [25]:
# joins .merge on key
df1=pd.DataFrame({'Keys':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Keys':['D','B','C'],'Value1':[4,7,10]})

pd.merge(df1,df2,on='Keys',how='inner')

  Keys  Value1_x  Value1_y
0    B         2         7
1    C         3        10